baseURL = "http://www.pigxw.top/"
languageCode = "zh-CN"
title = "小xiao潇的个人博客"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false


[Languages]
[languages.zh]
  languageCode = "zh-CN"
  languageName = "简体中文"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:filename/"

[menu]
  [[menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 1
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "联系我"
    url = "/contacts/"
    weight = 10
  [[menu.main]]
    name = "订阅"
    url = "/wechat-subscribe/"
    weight = 20


[params]
    since = 2019
    author = "小xiao潇"
    avatar = "/images/me/avatar.jpg"           
    subtitle = "成长记录 ， 记录成长"      
    cdn_url = ""           # Base CDN URL
    home_mode = "/content/my/resume.md" # post or other

    google_verification = ""

    description = "小xiao潇的个人网站" 
    keywords = "Vue,前端,程序猿"

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "WUXIAOd"
    Email   = "pigxw0106@gmail.com"
    Wechat = "/images/me/wechat.jpg"  